services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wp-database.c3c4222g6kve.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: wordpress123!
      WORDPRESS_DB_NAME: wp-database
    volumes:
      - /mnt/efs/wordpress:/var/www/html

